INSERT INTO teams (name, abbreviation) VALUES ('Atlanta Hawks', 'ATL');
INSERT INTO teams (name, abbreviation) VALUES ('Boston Celtics', 'BOS');
INSERT INTO teams (name, abbreviation) VALUES ('Brooklyn Nets', 'BKN');
INSERT INTO teams (name, abbreviation) VALUES ('Charlotte Hornets', 'CHA');
INSERT INTO teams (name, abbreviation) VALUES ('Chicago Bulls', 'CHI');
INSERT INTO teams (name, abbreviation) VALUES ('Cleveland Cavaliers', 'CLE');
INSERT INTO teams (name, abbreviation) VALUES ('Dallas Mavericks', 'DAL');
INSERT INTO teams (name, abbreviation) VALUES ('Denver Nuggets', 'DEN');
INSERT INTO teams (name, abbreviation) VALUES ('Detroit Pistons', 'DET');
INSERT INTO teams (name, abbreviation) VALUES ('Golden State Warriors', 'GSW');
INSERT INTO teams (name, abbreviation) VALUES ('Houston Rockets', 'HOU');
INSERT INTO teams (name, abbreviation) VALUES ('Indiana Pacers', 'IND');
INSERT INTO teams (name, abbreviation) VALUES ('Los Angeles Clippers', 'LAC');
INSERT INTO teams (name, abbreviation) VALUES ('Los Angeles Lakers', 'LAL');
INSERT INTO teams (name, abbreviation) VALUES ('Memphis Grizzlies', 'MEM');
INSERT INTO teams (name, abbreviation) VALUES ('Miami Heat', 'MIA');
INSERT INTO teams (name, abbreviation) VALUES ('Milwaukee Bucks', 'MIL');
INSERT INTO teams (name, abbreviation) VALUES ('Minnesota Timberwolves', 'MIN');
INSERT INTO teams (name, abbreviation) VALUES ('New Orleans Pelicans', 'NOP');
INSERT INTO teams (name, abbreviation) VALUES ('New York Knicks', 'NYK');
INSERT INTO teams (name, abbreviation) VALUES ('Oklahoma City Thunder', 'OKC');
INSERT INTO teams (name, abbreviation) VALUES ('Orlando Magic', 'ORL');
INSERT INTO teams (name, abbreviation) VALUES ('Philadelphia 76ers', 'PHI');
INSERT INTO teams (name, abbreviation) VALUES ('Phoenix Suns', 'PHX');
INSERT INTO teams (name, abbreviation) VALUES ('Portland Trail Blazers', 'POR');
INSERT INTO teams (name, abbreviation) VALUES ('Sacremento Kings', 'SAC');
INSERT INTO teams (name, abbreviation) VALUES ('San Antonio Spurs', 'SAS');
INSERT INTO teams (name, abbreviation) VALUES ('Toronto Raptors', 'TOR');
INSERT INTO teams (name, abbreviation) VALUES ('Utah Jazz', 'UTA');
INSERT INTO teams (name, abbreviation) VALUES ('Washington Wizards', 'WAS');